snapview/tungstenite-rs

src/protocol/mod.rs

one typo, one grammar thing that sounds like a German tried to write it as they would in German :) (being German myself...)
Cheers

improve doc in protocol/mod.rs

---

Cargo.toml

The tests won't pass until #29 is merged

Upgrade dependency versions

---

Cargo.toml
src/handshake/mod.rs

```
sha1sum program: 843.86 MB/s
sha-1 crate: 560.99 MB/s
sha1 crate: 340.62 MB/s
ring crate: 292.01 MB/s
```
https://gist.github.com/mehcode/79e718a07acb80a88c69961b9a30aa47
---
The tests won't pass until #29 is merged

Switch from sha1 to sha-1

---

src/protocol/frame/mod.rs
src/protocol/mod.rs

This PR extracts the implementation details in `protocol::WebSocket<S>` as a new struct `WebSocketContext`.
The motivation of this change is to allow handling WebSocket data when the provided I/O is borrowed and cannot be create the instance of `WebSocket`.

extract the context values from `WebSocket`

---

Cargo.toml
examples/callback-error.rs
src/handshake/server.rs
src/lib.rs

Signed-off-by: Alexey Galakhov <agalakhov@snapview.de>

server: let callback return HTTP error messages

---

src/protocol/mod.rs

I didn't notice yesterday, but it also swallows ping/pong frames. Since ping/pong frames can hold user data, it seems more consistent to also let them through.
I defer to the other PR to make them protocol errors, in line with the data frames.

Don't swallow ping/pong while waiting for close acknowledgement

---

src/protocol/mod.rs

This uses the new method to make some code briefer and some conditional simpler.
There are a few other places where `WebSocketState::ClosedByPeer | WebSocketState::CloseAcknowledged` exist, but because of the specific constructs in those places it's not convenient to replace them with `can_read`.

Make use of can_read to clean up some code

---

src/protocol/mod.rs

Signed-off-by: Alexey Galakhov <agalakhov@snapview.de>

websocket: add `can_read()` and `can_write()`

---

Cargo.toml
src/handshake/mod.rs

It would also be great to get a 0.11.1 bugfix release with this :)

Update to sha-1 0.9

---

README.md

The original code failed to compile with "expected item after doc comment" error message.

Make echo server compile

---

src/client.rs
src/protocol/message.rs

* Avoid unneeded temporary `fin`
* Delegate work in `into_client_request`

Some simplifications

---

src/error.rs
src/handshake/headers.rs
src/handshake/mod.rs
src/protocol/frame/frame.rs
src/protocol/message.rs
src/protocol/mod.rs

matches!: use macros; remove unused imports

---

src/error.rs

I guess this was just forgotten before? Seems like a pretty sensible impl to me :)

Add `From<ProtocolError>` impl for `Error`

---

src/error.rs
src/handshake/client.rs

if specify `host` in headers, will write `host` twice for `req`

fix: write some header twice

---

src/client.rs
src/error.rs
src/handshake/client.rs

Supersedes https://github.com/snapview/tungstenite-rs/pull/258.
Closes [#issuecomment-1016628264.](https://github.com/snapview/tungstenite-rs/issues/255).

client: overhaul of the request generation

---

scripts/autobahn-client.sh
scripts/autobahn-server.sh

This should fail because of #271.

Fix autobahn scripts

---

src/protocol/frame/mod.rs
src/protocol/mod.rs

Reverts snapview/tungstenite-rs#291

Revert "add support for batching websocket messages"

---

Cargo.toml
src/error.rs
src/lib.rs
tests/no_send_after_close.rs
tests/receive_after_init_close.rs

Make handshake dependencies optional.

---

Cargo.toml
src/tls.rs

Update `webpki-roots` to 0.25

---

src/protocol/frame/frame.rs

The byteorder dependency is only used in protocol::frame::frame. I thought this dependency could easily be removed and set out to replace the use of byteorder with equivalent std methods.
NetworkEndian is an alias for BigEndian. Converting a number like u32 to bytes can be done via the std lib via .to_be_bytes(). The opposite direction is from_by_bytes(). These simple things thus to not need byteorder.
There is one place in the code where byteorder actually helps, thus this dependency is not actually fully removed. ByteOrder::read_uint() allows to read 1 to 8 bytes of data and returns the result as u64. Doing this with the standard library basically requires re-implementing byteorder. Thus, I did not do that.
-----
Feel free to tell me that this is not useful and reject this. My original …

Reduce use of byteorder crate

---

CHANGELOG.md
Cargo.toml
src/tls.rs

This is a non-breaking change.

Update webpki-roots to 0.26

---

Cargo.toml
src/tls.rs

Draft until `rustls-native-certs` 0.7 is released.
Closes: #395 
Closes: #396

Update `rustls` to 0.22

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml

* Update thiserror to 2
* Update dev-dependencies
* Update `0.25.0` changelog with read optimisation entry.

Update thiserror to 2, update env_logger & update changelog

---

src/protocol/frame/mod.rs

Following on from discussion https://github.com/snapview/tungstenite-rs/pull/496#discussion_r2105518874 in `read_frame` we can reserve the full message length exactly once if we do it when we first successfully parse the message header. 
This also avoids the need for the `reserved_full_msg_len` flag previously introduced and will work even for messages requiring multiple `read_frame` calls (e.g. after `WouldBlock` errors).

When reading avoid over-reserving the in the case WouldBlock causes multiple read_frame calls

---

src/protocol/message.rs
src/protocol/mod.rs

A follow-up on https://github.com/snapview/tungstenite-rs/pull/515#issuecomment-3280499047.

refactor: simplify processing incoming data frames
