Cargo.toml
src/client.rs
src/handshake/server.rs
src/input_buffer.rs
src/protocol/frame/frame.rs
src/protocol/mod.rs

Some changes I made while playing with this library. Please see the commit messages.

Miscellaneous improvements

---

examples/autobahn-client.rs
examples/autobahn-server.rs
src/protocol/message.rs
src/protocol/mod.rs

This'll allow removal/deprecation of the `send_ping` custom method but also
allow applications to react to `Pong` messages as appropriate.
Closes #16

Add `Ping` and `Pong` variants to `Message`

---

Cargo.toml
README.md
examples/autobahn-client.rs
examples/autobahn-server.rs
examples/client.rs
examples/server.rs
src/client.rs
src/handshake/client.rs
src/handshake/headers.rs
src/handshake/mod.rs
src/handshake/server.rs
src/server.rs

Fixes #6.
The clients are now able to access the server's response upon websocket handshake. So now you can write:
`let (websocket, response) = connect(...);`
on a client side (compared to `let websocket = connect(...)` in the past).
Based on the #6 requirements/requests, the server-side is a bit more complicated, as the user wants to access the headers and either reject or continue the handshake based on the incoming headers, also the users want to be able to specity their own extra headers which are written by the server to the response on the client's request. Because of these requirements, the server's `accept()` function now accepts an optional `callback` parameter, so the user has a full control of whether the websocket connection is accepted or rejected, also the user can add extra …

Add support for altering request/response headers during the websocket handshake

---

README.md

These clarify what comes from `std` and what comes from `tungstenite`.

Add use statements to README.md example

---

Cargo.toml
src/handshake/client.rs

Take the "best from both worlds", i.e. merge `tungstenite::handshake::client::Request` and `tokio_tungstenite::Request` into one structure to avoid confusion and code duplication and also to allow the structure to be a bit more flexible than before (previous limitation for `tokio_tungstenite::Request` and `connect_async` made it impossible to pass `String` values in the header as only `&'static str` were allowed due to `BoxFuture` requirements of `+ static`).

Minor improvements in `Request`

---

Cargo.toml
examples/autobahn-client.rs
examples/autobahn-server.rs
examples/client.rs
src/handshake/client.rs
src/handshake/headers.rs
src/handshake/machine.rs
src/handshake/mod.rs
src/handshake/server.rs
src/lib.rs
src/protocol/frame/mod.rs
src/protocol/message.rs
src/protocol/mod.rs
src/stream.rs

Deny missing debug and resolve resulting errors to satisfy:
https://rust-lang-nursery.github.io/api-guidelines/debuggability.html#all-public-types-implement-debug-c-debug
Requires updated input_buffer pushed to crates.io:
- Resolved build errors by using github version of code until new version available on crates.io
Upgrade env_logger dev-dependency to v0.5.3
- Removed unwrap call from env_logger::init()  as it is no longer needed.

Derive Debugs

---

Cargo.toml
src/error.rs
src/protocol/mod.rs

I figured if anyone wants to buffer up messages, they can just use `Sink::buffer()`. If you like the idea of a configurable size `send_queue` I can do that instead.
Oh also I replaced some `replace()` (heh) calls with `take()`.

`WebSocket::write_message` only buffers one message at a time to apply back-pressure

---

src/protocol/frame/frame.rs

Since there is only one `unsafe` left outside of `frame/mask.rs`, I thought it'd be fun to try and get rid of it.
The reason for the unsafe was presumably to avoid copying or zero-initializing. This achieves the same but using only safe functions.
Note: there is no zero-initializing here because `Cursor` is "trusted" to not read from the buffer and so skips the initialization: https://github.com/rust-lang/rust/blob/master/src/libstd/io/cursor.rs#L241 (the `Take` wrapper delegates to its inner).

frame: eliminate an unsafe when reading message data into the buffer

---

Cargo.toml
examples/autobahn-client.rs
examples/autobahn-server.rs
src/protocol/frame/frame.rs
src/protocol/message.rs
src/protocol/mod.rs

It has been asked multiple times by other developers and mentioned in our GitHub issues, that we should support the possibility to retrieve the received the close code and also to be able to send close codes as a message (which is barely the only possible way to push messages to the sink when the one uses our `tokio-tungstenite`). We need to be able to retrieve the close messages not as an error, but as a regular message, because normal close is not considered an error and  This pull requests prepares the changes in `tungstenite-rs` for upcoming pull-request which fixes https://github.com/snapview/tokio-tungstenite/issues/45 and https://github.com/snapview/tokio-tungstenite/issues/51.
Summary:
1. Close has been added to the `Message` enum.
2. The behavior for when to return `Close` must …

Make `Close` part of the `Message` enum

---

Cargo.toml
src/protocol/mod.rs
tests/connection_reset.rs

@agalakhov please let me know when you publish this new version to crates.io, so that I can update `tokio-tungstenite` to use the new dependency.

Fix error `ConnectionClosed` never returned to server when server initiated close

---

Cargo.toml
examples/autobahn-client.rs
examples/autobahn-server.rs
examples/callback-error.rs
examples/client.rs
examples/server.rs
fuzz/Cargo.toml
src/client.rs
src/error.rs
src/handshake/client.rs
src/handshake/headers.rs
src/handshake/machine.rs
src/handshake/mod.rs
src/handshake/server.rs
src/lib.rs
src/protocol/frame/coding.rs
src/protocol/frame/frame.rs
src/protocol/frame/mask.rs
src/protocol/frame/mod.rs
src/protocol/message.rs
src/protocol/mod.rs
src/server.rs
src/stream.rs
src/util.rs
tests/connection_reset.rs

I have not touched any unsafe code and just left them quarantined within `#[allow]` blocks.

Edition 2018, formatting, clippy fixes

---

src/protocol/mod.rs
tests/no_send_after_close.rs

> The application MUST NOT send any more data frames after sending a Close frame.
src: _[The websocket RFC - section 5.5.1 Close](https://tools.ietf.org/html/rfc6455#section-5.5.1)_
Tungstenite did not comply here. This PR fixes this. There is an integration test provided that guarantees that it works.
Closes: snapview/tokio-tungstenite#67
Note that this builds upon #72, there are only 3 commits in this PR, the others are from #72.
WARNING: This is a BREAKING CHANGE

Do not allow sending messages after sending a close frame

---

src/error.rs
src/protocol/mod.rs

So as I have been figuring out from the source code how tungstenite works, I felt it would be silly to just let that disappear when my memory fades, so I wrote documentation, hoping it will also save others time.
This isn't polished:
- `read_message`, `write_pending` and `close` should probably have an Errors section which lists all the possible outcomes
- some of it can hopefully be simplified after other issues are resolved, like: #78. 
- some of the error handling hasn't actually been resolved, like: #74 and the docs will need updating when it does 
- design improvements might make things more convenient, like: #76 which might also change behavior as described here.
- `write_pending` is a user facing method that does not use `check_active`. I haven't really dug into what that really …

WIP: Add some documentation to WebSocket and Error.

---

README.md

The example in the main README doesn't compile:
```
error[E0061]: this function takes 1 parameter but 2 parameters were supplied
|
|             let mut websocket = accept(stream.unwrap(), None).unwrap();
|                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 1 parameter
```
The current [`accept()` function](https://docs.rs/tungstenite/0.9.1/tungstenite/server/fn.accept.html) seems to take only one parameter.
I'm guessing that `None` is a carry-over from `accept_hdr()`, which has a [header processing callback](https://docs.rs/tungstenite/0.9.1/tungstenite/server/fn.accept_hdr.html).

Fix typo in README.md example

---

Cargo.toml
examples/autobahn-client.rs
examples/callback-error.rs
examples/client.rs
examples/server.rs
src/client.rs
src/error.rs
src/handshake/client.rs
src/handshake/headers.rs
src/handshake/server.rs
src/protocol/frame/mod.rs
src/protocol/message.rs
src/protocol/mod.rs
tests/no_send_after_close.rs

Fixes https://github.com/snapview/tungstenite-rs/issues/92
Also contains some minor cleanup in separate commits.

Base HTTP-types (request, headers, response, status code, etc) on the ones from the http crate

---

src/handshake/server.rs

When connecting, firefox always sends `Connection: keep-alive, Upgrade` header, so connection is always rejected

Allow firefox to connect

---

src/protocol/frame/frame.rs

Without the ability to get the mask, having the `FrameHeader` struct as a public type along with functions like `parse` is somewhat useless. I can't see any reason why it shouldn't be public.

Make mask public on FrameHeader

---

src/protocol/frame/coding.rs

As stated in standard library documentation:
> One should always prefer implementing From over Into because implementing From automatically
> provides one with an implementation of Into thanks to the blanket implementation in the standard library.
The idea of this implementation to make possible to use `u16::from(close_code)` in closure

Change Into to From for CloseCode to u16 conversation

---

src/protocol/frame/mask.rs

This reduce number of usage of `unsafe` in crate to just 1.
Plus I made benchmark (you can find benchmark [here](https://github.com/Dushistov/tungstenite_apply_mask_bench) (**it requires nightly**) ),
and it should be also faster now:
| ptr offset  | fallback (ns) | old fast32 (ns) | new fast32 (ns) |
| ------------- | ------------- | ------------- |  ------------- |
| 0  | 24.727  | 11.963 | 7.9807 |
| 1  | 25.710  | 20.476 | 9.3833 |
| 2 | 16.160 | 20.569 | 9.1830 |
| 3 | 15.548 | 18.867 | 8.3566 |

Make tungstenite-rs more safe

---

Cargo.toml

Solving https://github.com/snapview/tungstenite-rs/issues/118 by using `features= ["tls-vendored"]` in the toml file

Allow statically linking

---

src/handshake/client.rs

[RFC6445 Sec11.3](https://tools.ietf.org/html/rfc6455#section-11.3) specifies several headers like `Sec-WebSocket-Protocol`. While it does not specifies the key should be case insensitive, many server only accepts case sensitive requests. However [http](https://docs.rs/http/0.2.1/http/) case every key to lowercase for convince. [hyper](https://docs.rs/hyper/0.13.5/hyper/) has an issue to solve this problem (https://github.com/hyperium/hyper/issues/1492), but not in http. This is a workaround to make the websocket server happy.

Fix ws request subportocol lowercase header

---

src/protocol/mod.rs

If preferred to avoid abbreviations, it could be called mebibytes.

doc: be precise about max message sizes.

---

src/handshake/server.rs

The impl of Display for StatusCode already includes the canonical reason
if it exists. The current implementation duplicates this (e.g. the
status line will read "101 Switching Protocols Switching Protocols", or
"400 Bad Request Bad Request".

Deduplicate the reason line in HTTP responses

---

src/client.rs
src/error.rs
src/handshake/client.rs
src/handshake/server.rs
src/protocol/mod.rs

Adds Error::Redirection, which is a special case of Error::Http that
extracts the redirection target from the response headers, and stores it
in the error object. Client implementations that build upon tungstenite
can use this to implement redirecting. The connect() function defined in this crate will automatically follow
redirecting responses. Its error handler causes it to recurse when a value of Error::Redirection is returned.
A catch-all solution for redirects is not possible due to the
abstraction transforming socket types to Read + Write, implementations
that use the client_* methods need to handle redirections themselves.

Add facilities to allow clients to follow HTTP 3xx redirects

---

Cargo.toml
src/handshake/machine.rs

blocked by: snapview/input_buffer#4 and release of input_buffer v0.4
closes: #162

Update to bytes 1.0

---

src/client.rs
src/handshake/server.rs

I'd like to build my reponse so I can feed it into my own http pipeline, that's impossible without having the ability of getting a `Reponse<T>`

Add a custom response builder

---

src/client.rs

This a relic of the old name in the function documentation.

Docfix: mio::tcp has been renamed to mio::net in its latest version

---

src/handshake/server.rs

Just a tiny change to remove a remaining usage of dynamic dispatch as mentioned in #141.
Closes #141.

Remove remaining dynamic dispatch usage

---

Cargo.toml

`input_buffer` 0.4.0 was released today. This changes from a direct git dependency to the official version.

Update input_buffer to use the official version

---

examples/srv_accept_unmasked_frames.rs
src/protocol/mod.rs

This change will make possible for websocket server to accept unmasked frames. This is needed since some legacy commercially used solutions are unfortunately violating  RFC 6455 and sending (acting as websocket clients)  unmasked client frames. Example is **_Asterisk AudioFork_** (https://github.com/nadirhamid/asterisk-audiofork) used in asterisk based telephony solutions. 
Also other widely used websocket implementations (e.g. **_Node.JS WS_** library - https://www.npmjs.com/package/ws) allow to create WS servers accepting unmasked client frames.

WebSocketConfig extended to allow accepting unmasked client frames

---

CHANGELOG.md
Cargo.toml
README.md
src/client.rs
src/error.rs
src/handshake/client.rs
src/handshake/machine.rs
src/handshake/server.rs
src/protocol/frame/coding.rs
src/protocol/frame/frame.rs
src/protocol/frame/mod.rs
src/protocol/message.rs
src/protocol/mod.rs
tests/no_send_after_close.rs

The current tungstenite error system doesn't allow for easily matching specific protocol, URL, and capacity errors due to use of string messages to distinguish different error subtypes. As such, I've created distinct enums for the different protocol, URL, and capacity errors that may occur.
To give an example of how this would be useful, imagine a scenario where one wants to check if an operation failed due to the remote host closing the connection without performing the closing handshake. Currently, one may write `Err(Error::Protocol(vioation)) if vioation.contains("closing handshake") => { ... }` or similar. With my new change, they now may write `Err(Error::Protocol(ProtocolErrorType::ResetWithoutClosingHandshake)) => { ... }` instead. This is both more efficient as it avoids comparing …

Create specific error types for protocol, URL, and capacity errors

---

CHANGELOG.md
src/handshake/client.rs
src/handshake/mod.rs
src/handshake/server.rs

This PR renames `convert_key` to `derive_accept_key` and exposes it as a public API. This makes it easier to manually perform a handshake before passing the TCP stream to `WebSocket::from_raw_socket`.
Also, thanks for this crate. It's very useful :)

Expose `handshake::derive_accept_key` as public API.

---

CHANGELOG.md
Cargo.toml
README.md
src/client.rs
src/error.rs
src/lib.rs
src/server.rs
src/stream.rs
tests/connection_reset.rs

This PR adds `rustls` as an alternative to the current `native-tls`. In addition, I changed the default feature set to not include any TLS implementation which is a breaking change as people have to add the TLS feature explicitly now.
I'm not sure what way you prefer to have the feature set so I will adjust to the way you prefer once you let me know.
Resolves #89.

Add support for rustls as TLS backend

---

src/error.rs

This PR implements `From<CapacityError>` and `From<UrlError>` for `Error`. I think that concludes all logical `From` implementations for `Error`.

Implement From<CapacityError> and From<UrlError> for Error.

---

Cargo.toml
src/client.rs

rustls 0.19 still uses webpki 0.21, and webpki 0.22 contains breaking changes so webpki must be downgraded. This PR also changes it so that rustls-native-certs is used instead of webpki-roots (related #203).

downgrade webpki, use rustls-native-certs instead of webpki-roots

---

Cargo.toml
benches/buffer.rs
src/buffer.rs
src/client.rs
src/error.rs
src/handshake/machine.rs
src/handshake/mod.rs
src/lib.rs
src/protocol/frame/mod.rs

Fixes https://github.com/snapview/tungstenite-rs/issues/210.
Please [check the discussion and decision](https://github.com/snapview/input_buffer/issues/6#issuecomment-870548303) if you don't know the context as well as the [latest PR in `input_buffer`](https://github.com/snapview/input_buffer/pull/9).
It seems like the new simplified implementation has only significant difference on x86_64 architecture while the changes on Armv8.4-A A64 (Apple M1) are not that significant as both versions perform really well. On ARM the new version even behaves a bit slower (but not significantly slower), however the difference on Intel (x86_64) architecture is quite significant.
```
===== M1 Mac (Armv8.4-A A64) =====
buffers/InputBuffer     time:   [543.66 us 549.32 us 555.54 us]
thrpt:  [7.0315 GiB/s …
```

Faster implementation of `InputBuffer`

---

CHANGELOG.md
Cargo.toml
src/client.rs
src/error.rs
src/stream.rs
tests/connection_reset.rs

Add feature flags for different providers of root certificates as discussed in #215. As mentioned in the issue `rustls` still uses the `0.21` version of `webpki`, that's why the `0.22` version wasn't used here. There's already a `0.20.0-beta2` of `rustls` so after some waiting that issue might be solved with an upgrade of rustls. As that new version brings many breaking changes, I didn't upgrade to the beta version for now.

Enable root cert providers through feature flags

---

rustfmt.toml
src/buffer.rs
src/protocol/frame/coding.rs
src/protocol/frame/frame.rs
src/protocol/message.rs

This fixes warnings by lates clippy and replaces deprecated settings from `rustfmt`.
Also, I added a `TryFrom` implementation for `Message -> String` as that seemed the only one missing in the list of conversion implementations for `Message`.

Fix clippy warnings and deprecated settings

---

Cargo.toml
examples/srv_accept_unmasked_frames.rs
src/client.rs
src/error.rs
src/lib.rs
src/stream.rs
src/tls.rs
tests/connection_reset.rs

This is mostly a backport of what was done in `tokio-tungstenite` by adding a connector. It allows to pick which TLS variant to use and further change the used configuration. That feature was initially discussed in #185. In addition it should solve the request described in #203.
Fixes #185, fixes #203.

Add a connector to configure TLS config

---

Cargo.toml
src/handshake/client.rs

This is currently blocking us for [upgrading kube-rs](https://github.com/kube-rs/kube-rs/pull/839), since we have some build time regressions on rustc 1.57-1.58.

Downgrade MSRV to 1.56

---

src/handshake/client.rs

While HTTP headers should be case-insensitive, unfortunately some servers don't conform to that behavior. Unfortunately, the `http` crate always stores headers in lowercase without any way to prevent that behavior, so if we run into a server that does not conform to spec, we're doomed.
This is a workaround to that issue - it changes the `origin` header into `Origin`.

fix: uppercase origin header

---

src/protocol/frame/mod.rs
src/protocol/mod.rs

Adds support for sending multiple messages with a single write call
* Adds a new function for appending messages without trying to write them to the socket immediately. 
* This allows for a significant improvement to throughput and latency by avoiding calling write for each individual message.

add support for batching websocket messages

---

src/protocol/frame/mod.rs
src/protocol/mod.rs

We've recently [had a new PR](https://github.com/snapview/tungstenite-rs/pull/291) that added some useful things but unfortunately caused a regression in the queue logic. The PR was consequently reverted, but one of the key learnings was that we did not have a queue logic covered by a test.
It would be nice if we had a test in place to cover this case. This PR adds such a test. Having this test would allow us to rebuild the desired logic in the correct way while keeping the queue logic sound.

tests: add a regression test for the queue logic

---

examples/callback-error.rs
src/error.rs
src/handshake/client.rs
src/handshake/server.rs

modified `client::Response` type to contain `String` instead of `()` to achieve this.
I ran into this issue yesterday when my automated test suite failed unexpectedly. Notably, fixing this doesn't conflict with RFC 6455, or RFC 2616.
> If the status code received from the server is not 101, the
client handles the response per HTTP [[RFC2616](https://www.rfc-editor.org/rfc/rfc2616)] procedures.  In
particular, the client might perform authentication if it
receives a 401 status code; the server might redirect the client
using a 3xx status code (but clients are not required to follow
them), etc.  Otherwise, proceed as follows.
So I've given it a shot. Modified `Response` to wrap a `String` instead of `()` - a significant breaking api change. Would it be better to return a `Vec<u8>` or `Cow`? …

Error response on client type returns request body upon non receiving non 101 status code from server

---

Cargo.toml
src/handshake/client.rs
src/handshake/mod.rs

base64 0.21 deprecated the simple API and requires quite a bit more code for the simple usage here, while data-encoding provides exactly the API needed and is also actively maintained.

Switch from base64 0.20 to data-encoding 2

---

src/protocol/message.rs

Simple typo fix of is_close() method comment

docs: message.rs comment typo

---

src/protocol/frame/frame.rs

Current behavior (example):
```
2023-02-11T23:09:47.255396Z TRACE tungstenite::protocol::frame: received frame
<FRAME>
final: true
reserved: false false false
opcode: BINARY
length: 45
payload length: 43
payload: 0x8374000464016464036e696c64026f7061b64017364036e696c64017464036e696c
```
See https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d306cadb79c84629d4b92b41bbaf8bd6 for how this PR (should) change this output. Big warning that I have not tested this, because the fix seems trivial.

Display correct payload in Frame::fmt

---

.gitignore
.travis.yml
Cargo.toml
README.md
autobahn/expected-results.json
examples/autobahn-client.rs
examples/autobahn-server.rs
examples/srv_accept_unmasked_frames.rs
scripts/autobahn-client.sh
scripts/autobahn-server.sh
src/error.rs
src/extensions/compression/deflate.rs
src/extensions/compression/mod.rs
src/extensions/mod.rs
src/handshake/client.rs
src/handshake/server.rs
src/lib.rs
src/protocol/frame/frame.rs
src/protocol/message.rs
src/protocol/mod.rs

Supersedes #235.
- Adds optional de/compression logic on top of the existing flow without any _major_ breaking changes.
- `permessage-deflate` is not enabled by default and requires a `deflate` feature.
- `client_max_window_bits` and `server_max_window_bits` are not supported yet because these require `flate2/zlib` which is not pure Rust.
- Passes Autobahn except for 13.3 to 13.6. These require supporting max window bits.
- Correct extension negotiation. The server declines invalid offers, and the client errors on invalid response to terminate the connection.
- `Sec-WebSocket-Extensions` header is parsed by `headers`
- https://github.com/snapview/tokio-tungstenite/pull/251
- Clean `warp` integration: https://github.com/seanmonstar/warp/pull/1016
I might need to adjust some code depending …

Add `permessage-deflate` support

---

Cargo.toml
src/tls.rs

Fix not compiling features rustls-tls-native-roots and rustls-tls-webpki-roots

---

Cargo.toml
src/error.rs

The error variant is no longer needed since `rustls` 0.21.

Remove unused `TlsError::Webpki` error variant

---

src/tls.rs

Same changes as in https://github.com/snapview/tokio-tungstenite/pull/283
Before this patch, the `rustls::RootCertStore::add` method was used to add all the root certificates found by `rustls_native_certs` crate. This is a problem when an ancient or invalid certificate is present in the native root store. `rustls` documentation says the following:
> This is suitable for a small set of root certificates that
> are expected to parse successfully. For large collections of
> roots (for example from a system store) it is expected that
> some of them might not be valid according to the rules `rustls`
> implements. As long as a relatively limited number of certificates
> are affected, this should not be a cause for concern. Use
> `RootCertStore::add_parsable_certificates` in order to add as many …

Gracefully handle invalid native root certificates

---

.gitignore
CHANGELOG.md
Cargo.toml
README.md
benches/write.rs
examples/autobahn-client.rs
examples/autobahn-server.rs
examples/client.rs
examples/server.rs
examples/srv_accept_unmasked_frames.rs
fuzz/fuzz_targets/read_message_client.rs
fuzz/fuzz_targets/read_message_server.rs
src/error.rs
src/protocol/frame/mod.rs
src/protocol/message.rs
src/protocol/mod.rs
tests/connection_reset.rs
tests/no_send_after_close.rs
tests/receive_after_init_close.rs

My context: I've been working on a websocket load generator service that will write lots of small json message events to it's ws clients. I was interested in having a high peak throughput from this service to allow me to test downstream load performance. It uses axum->tokio-tungstenite->tungstenite. Doing localhost testing I got **~1.2M msg/s** peak throughput. This PR improves that to **~2M msg/s**.
Because of this improvement I thought this PR may be worthwhile.
I noticed there was a lot of flushing happening. Currently flushing is done something like:
* Before writing each message.
* After writing each message.
* Before reading each message.
This seems excessive particularly when trying to send batches of lots of small messages. This PR minimises flushes so that a flush will only occur …

Rework to remove implicit flushes

---

CHANGELOG.md
benches/write.rs
src/protocol/frame/mod.rs
src/protocol/mod.rs
tests/write.rs

Add ability to buffer multiple writes before writing to the underlying stream, controlled by `WebSocketConfig::write_buffer_size` (default 128 KiB). Improves batch message write performance.
This PR comes out of some further investigation this morning regarding writing many small messages. After #357 we no longer flush on each write which gives a big boost. I wondered what would happen if we also avoided/minimised `write` calls to the underlying stream and allowed the messages to buffer in the out_buffer/write buffer.
In short it does seem to provide a boost, though not as dramatic as the flush rework. With #357 my load-generator could write **~2.15M msg/s**, with 128KiB write_buffer_size this goes up to **~2.44M msg/s**.
Larger sizes didn't yield a benefit for me so 128KiB seems a decent …

Buffer writes before writing to the underlying stream

---

src/client.rs

Attempting to use URLs like `ws://[::1]:8080/ws` was giving me "Name or service not known". I adapted https://github.com/sdroege/async-tungstenite/pull/100 to produce this fix which works for me.

remove [] enclosing IPv6 host address

---

src/handshake/client.rs

Why: 
Using `WrongHttpMethod` for this error leads to misleading error messages
How:
Use correct error

Return correct protocol error when missing http version

---

src/protocol/mod.rs

Based on conversations in https://github.com/snapview/tokio-tungstenite/issues/286 & https://github.com/snapview/tokio-tungstenite/pull/287 this PR attempts to clarify the `WebSocketConfig` docs around write-buffer behaviour.

Clarify `WebSocketConfig` docs

---

CHANGELOG.md
src/protocol/mod.rs

Based on hypotheticals in https://github.com/snapview/tokio-tungstenite/issues/286 & https://github.com/snapview/tokio-tungstenite/pull/287 this PR asserts that `WebSocketConfig::max_write_buffer_size` must be greater than `WebSocketConfig::write_buffer_size`.
Doing otherwise is a configuration mistake as writes would not be able function without errors.
Previously it was just docs, since if misconfigured the user would simply get lots of `WriteBufferFull` errors. I _think_ this panic will be better as it will inform the user and point them in the direction of the docs instead of thinking this behaviour a tungstenite bug?
We could instead move `WebSocketConfig` to a builder style, so itself could panic which puts the panic a bit closer to the source. But that's more of a change and may …

Add assert panics for `WebSocketConfig`

---

README.md

The test suite webpage no longer appears to be online so this links to the GitHub page instead.

Update Autobahn Test Suite page

---

Cargo.toml
tests/connection_reset.rs

Replace deprecated `net2` dev dependency with `socket2`

---

CHANGELOG.md
src/protocol/mod.rs
tests/auto_pong_flush.rs

Currently auto pongs are written and flushed during `read()`. If a `WouldBlock` error is received it is ignored and reading continues.
In the case the usage is read-predominant, this presents a scenario where the auto pong is `WouldBlock`-ed and will never retry flushing until another ping is received or the client does some unrelated writes. This could cause the other connected party to time out the connection as it has failed to receive a timely pong response.
I reproduced this in new test `read_usage_auto_pong_flush`.
To fix we record if a pong write failed in this way and retry on all subsequent `read` calls until a flush succeeds.

Fix auto pong responses not flushing after block

---

.github/workflows/ci.yml
Cargo.toml

The code does not actually compile anymore with 1.51.
Also only run `cargo check` with 1.60 as various optional features, tests, benchmarks actually require newer Rust versions.

Update MSRV to 1.60 and check on the CI

---

src/client.rs
src/lib.rs
tests/client_headers.rs

Added a `ClientRequestBuilder` type inspired by [websockets](https://docs.rs/websockets/latest/websockets/struct.WebSocketBuilder.html) to allow for additional header values in the request, like authorization or subprotocols.
The way I implemented this is not the cleanest but I wanted to avoid any breaking change.
This is merely a proposal, so feedback welcome !

Add builder for additional header values

---

src/handshake/server.rs

This makes it more possible to use the library handshake creation when the request and response body types differ.

handshake: server: Make 'create_response_with_body' function more generic

---

Cargo.toml

Before releasing 0.22, I believe we should change how we depend on rustls.
Since rustls swapped to having multiple backends, we need to set `default-features = false` for rustls so that the user of tungstenite is free to choose the rustls backend.
This is particularly important since the new default backend for rustls does not build in many environments due to older version of gcc.
This PR needs to land before 0.22 since its a breaking change.
The `std` feature is enabled since it is [enabled by default](https://github.com/rustls/rustls/blob/4e2856b1fa4917a6a8c35c5c4aada1f5fd649cc5/rustls/Cargo.toml#L31) and required for tungstenite's rustls feature to compile at all
There is currently a PR open against tokio-tungstenite to do the same …

Set default-features = false for rustls

---

src/client.rs
tests/wss_fails_when_no_tls.rs

Hi,
When compiled without TLS support, the client currently falls back to HTTP (and by default, on port 443) even if the URI has the `wss` scheme. This creates a problem that is hard to debug, as the call fails with a  generic WSS protocol error.
If a `wss://` URI is requested and no TLS support is available, the client should fail fast with a `UrlError::TlsFeatureNotEnabled`.
Cheers,

Fix behavior when connecting wss url without TLS support

---

Cargo.toml
src/tls.rs

The `load_native_certs()` function now returns all errors instead of raising only the first error.
Not finding any native root CA certificates is not fatal if the "rustls-tls-webpki-roots" feature is enabled.

deps: update `rustls-native-certs` to 0.8

---

.github/workflows/ci.yml

This fixes the deprecation messages in the CI build summary.

ci: update `actions/checkout` action to v4

---

.github/workflows/ci.yml
benches/buffer.rs
benches/write.rs
examples/autobahn-client.rs
examples/client.rs
examples/server.rs
examples/srv_accept_unmasked_frames.rs
src/buffer.rs
src/client.rs
src/handshake/client.rs
src/handshake/server.rs
src/protocol/frame/frame.rs
src/protocol/frame/mask.rs
src/protocol/frame/mod.rs
src/protocol/mod.rs
src/stream.rs
src/tls.rs
src/util.rs
tests/connection_reset.rs
tests/wss_fails_when_no_tls.rs

This PR fixes the current default clippy warnings and some selected warnings from the `clippy::pedantic` group.
It also adds an additional CI build job for clippy as suggested in https://github.com/snapview/tungstenite-rs/pull/434#pullrequestreview-2235867363.

Fix clippy warnings & add CI build job for clippy

---

Cargo.toml
src/client.rs
src/protocol/message.rs
src/tls.rs

The Rust edition can be updated to 2021 (1.56.0) because the MSRV is 1.63.0.

Update to Rust edition 2021

---

src/client.rs
src/protocol/frame/frame.rs
src/stream.rs

The latest stable clippy has new lints. In two commits, I solved the new lints.
I suggest using a fixed clippy version to prevent future breakage. If you are interested, I could do that in a separate PR.

Resolve clippy issues

---

src/handshake/client.rs
tests/handshake.rs

This trims optional whitespace when extracting the advertised protocols from the client request, which is required to later verify that the server's response matches one of the protocols.
Fixes https://github.com/snapview/tungstenite-rs/issues/456

Trim optional separating whitespace in client protocols

---

benches/read.rs
benches/write.rs

I noticed `slice::to_vec` seems to be faster than `.into()` :shrug:. This code is also more compatible with the proposed approach in #462 
As this generates vec data faster it makes the bench faster (but just the bench) .
```
write 100k small messages then flush (server)
time:   [4.0320 ms 4.0390 ms 4.0672 ms]
change: [-8.8302% -8.3994% -7.9684%] (p = 0.05 > 0.05)
write+mask 100k small messages then flush (client)
time:   [5.3872 ms 5.3921 ms 5.4115 ms]
change: [-8.0997% -7.6006% -7.0983%] (p = 0.07 > 0.05)
```

Bench: optimise binary data generation

---

Cargo.toml
benches/read.rs
benches/write.rs
examples/autobahn-client.rs
src/lib.rs
src/protocol/frame/frame.rs
src/protocol/frame/mod.rs
src/protocol/frame/payload.rs
src/protocol/message.rs
src/protocol/mod.rs

This PR builds on top of #462 
* Adds `Utf8Payload` for text messages backed by `Payload`.
* Tri-variant `Payload` for `Bytes`, `BytesMut` & `Vec`.
- `Bytes` gives flexibility supporting shared data & cheap cloning.
- `BytesMut` provides best read performance as we can get these from the new read buffer sans copying & unmask optimially too.
- `Vec` provides best write performance. I couldn't get `BytesMut` to perform as well even changing the bench user code. Since it doesn't increase Payload 40 bytes size it seems worth having.
* Replace the read buffer with a `BytesMut` based one that can then emit payloads without copying.
* Optimise incomplete message handling so complete messages do not need to be copied (general case for small messages).
* Add `Payload::share` for cheap cloning.
* …

Support `bytes::Bytes` & `bytes::BytesMut` payloads for binary & text messaging

---

src/protocol/frame/payload.rs

Bytes::from_owner is "generic" method, for any "owners" of [u8], while specialized "impl From<Vec<u8>> for Bytes" can be faster in some cases, for example if Vec::capacity==Vec::len, then it is almost no-op.

tiny optimization: use more optimized method for Vec<u8> to Bytes conversation

---

CHANGELOG.md
examples/srv_accept_unmasked_frames.rs
src/protocol/frame/mod.rs
src/protocol/mod.rs
tests/write.rs

- Add `WebSocketConfig::read_buffer_size` default 128 KiB.
- Make `WebSocketConfig` non-exhaustive & add builder style construction fns.
- Remove deprecated `WebSocketConfig::max_send_queue`.
Note this also doubles the read buffer len in https://github.com/snapview/tungstenite-rs/pull/465 from 64 -> 128k providing a boost in bench perf, since the bench has 100k messages ready to go.
The bench is a bit artificial to deduce the best default, but 128k is the current default for the write buffer so seems a good place to start.
```
read+unmask 100k small messages (server)
time:   [7.5623 ms 7.5700 ms 7.6009 ms]
change: [-3.5836% -3.0376% -2.4881%] (p = 0.07 > 0.05)
read 100k small messages (client)
time:   [7.1301 ms 7.1658 ms 7.1747 ms]
change: [-4.4713% -2.4551% -0.3652%] (p = 0.13 > 0.05) …
```

Add `WebSocketConfig::read_buffer_size` default 128 KiB

---

src/protocol/frame/mod.rs

Minor optimisation of read buffer logic using `set_len` to avoid writing zeroes, more worthwhile if configuring large read buffer sizes.
Also simplified the code a bit using the buffer directly instead of split_off + unsplit.

Use set-len when reading into buffer

---

src/protocol/message.rs

https://github.com/snapview/tungstenite-rs/blob/fb9c15417813f0c2f3209e22eece309544895d79/src/protocol/message.rs#L186
here it should say `Bytes`, not `Vec<u8>`, didn't catch this yesterday.

message: fix documentation on Message::binary()

---

src/protocol/frame/mod.rs

The refactored read_in seems easier to read. But I guess it isn't a big deal either way. Feel free to close if you don't want it. 
Relates to discussion in https://github.com/snapview/tungstenite-rs/pull/471

Minor: Keep read_in refactor sans set-len

---

src/protocol/frame/utf8.rs

I'm in a case where I already have a `Utf8Bytes` equivalent in my own codebase (a simple `Bytes` wrapper), therefore I am sure that this [`Bytes`] is valid utf8 data and I want to convert it to a `Utf8Bytes`.
However there is currently now way to construct a `Utf8Bytes` without checking the encoding even if we are sure about it.
I propose to add the `from_bytes_unchecked` which is similar to `String::from_utf8_unchecked`.

feat: add unsafe Utf8Bytes::from_bytes_unchecked

---

Cargo.toml
src/protocol/frame/frame.rs

`byteorder` was only used in one place and since bytes crate implements similar functionality it lets us drop it pretty easily.

Remove byteorder, use bytes::Buf::get_uint instead

---

CHANGELOG.md
src/protocol/mod.rs

- Add `WebSocketConfig::read_buffer_size` docs explaining performance/memory tradeoff.
- Update 0.25.0 changelog explaining change to memory use.
Relates to #480

Add `WebSocketConfig::read_buffer_size` docs explaining performance/memory tradeoff

---

src/protocol/frame/utf8.rs

As mentioned in documentation of rust standard library, if a type implements both [`Borrow`](https://doc.rust-lang.org/nightly/std/borrow/trait.Borrow.html) and [`Hash`](https://doc.rust-lang.org/nightly/std/hash/trait.Hash.html), they should be consistent: `hash(x) == hash(x.borrow())`, (cf. https://rust-lang.github.io/rust-clippy/master/index.html#impl_hash_borrow_with_str_and_bytes)
However, the current implementation is not consistent. It may cause unexpected behaviors when using HashMap for these.

Hash consistency for Borrow + Hash traits for Utf8Bytes

---

src/protocol/message.rs

Implementation `From<Bytes>` for `Message` is missing.
The internal representation of the binary message is `Bytes`. It would be convenient to have related `From` implementation, especially for application code that is designed to work with `Bytes` as opposed to `Vec<u8>`.

Implement `From<Bytes>` for `Message`

---

Cargo.toml
README.md
benches/buffer.rs
benches/e2e.rs

Introduce e2e.rs containing end to end style benchmarks using a real `std::net::TcpListener`.
Run with `cargo bench --bench e2e -- --quick --noplot`.
The benchmarks sets up a very simple ws server & client and sends a single message client->server, the server sends a single response server->client (not an echo!).
This means the bench should provide good regression coverage of end to end text message performance.
This benchmark is configured to run at varying sizes 512 B up to 1 GiB. As such it highlights #493, current output
```
send+recv/512 B         time:   [13.049 µs 13.187 µs 13.222 µs]
thrpt:  [73.860 MiB/s 74.053 MiB/s 74.838 MiB/s]
send+recv/4 KiB         time:   [15.441 µs 15.544 µs 15.955 µs]
thrpt:  [489.67 MiB/s 502.60 MiB/s 505.95 MiB/s]
send+recv/32 KiB        time: …
```

Add end to end "send+recv" benchmarks

---

examples/autobahn-client.rs
src/protocol/frame/frame.rs
src/protocol/message.rs
tests/auto_pong_flush.rs
tests/client_headers.rs
tests/connection_reset.rs
tests/no_send_after_close.rs
tests/receive_after_init_close.rs

This fixes all current clippy warnings.

Fix clippy warnings: Inline `format!` args
